name: Spell Check

on:
  push:
    paths:
      - "**.el"
      - ".github/workflows/spellcheck.yml"
  pull_request:
    paths:
      - "**.el"
      - ".github/workflows/spellcheck.yml"

jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install aspell
        run: sudo apt-get update && sudo apt-get install -y aspell aspell-en

      - name: Spell check Emacs Lisp comments and strings
        run: |
          # Spell check .el files using aspell with context filters
          find . -name "*.el" -exec cat {} + | \
            aspell list \
              --ignore-case \
              --add-filter=context \
              --add-context-delimiters='; \0' \
              --rem-context-delimiters='" "' \
              --personal=./.github/aspell-dict | \
            sort -u > misspelled_words.txt

          if [ -s misspelled_words.txt ]; then
            echo "::error::Misspelled words found:"
            cat misspelled_words.txt
            exit 1
          else
            echo "No misspelled words found"
          fi